WITH JAUNARY_SALES AS(
    SELECT
        BOOK_ID,
        SUM(SALES) AS TOTAL_SALES
    FROM
        BOOK_SALES
    WHERE
        SALES_DATE LIKE "2022-01%"
    GROUP BY
        BOOK_ID
)

SELECT
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * J.TOTAL_SALES) AS TOTAL_SALES
FROM
    BOOK B
JOIN
    JAUNARY_SALES J
ON
    B.BOOK_ID = J.BOOK_ID
JOIN
    AUTHOR A
ON
    B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY
    AUTHOR_NAME,CATEGORY
ORDER BY
    AUTHOR_ID,CATEGORY DESC