-- 코드를 작성해주세요
SELECT B.ID
    ,IFNULL(R.CHILD_COUNT,0) AS CHILD_COUNT
FROM ECOLI_DATA B
LEFT JOIN(
    SELECT PARENT_ID
        ,COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
    ) AS R
ON B.ID = R.PARENT_ID
ORDER BY B.ID