-- 코드를 입력하세요
SELECT PRODUCT_CODE
    ,B.PRICE * P.TOTAL_AMOUNT AS SALES
FROM PRODUCT AS B
JOIN (
    SELECT PRODUCT_ID
        ,SUM(SALES_AMOUNT) AS TOTAL_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) AS P
ON P.PRODUCT_ID = B.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE