# SELECT
#     *
#     COUNT(*)
# FROM 
#     ONLINE_SALE B
# JOIN
#     USER_INFO R
# ON
#     B.USER_ID = R.USER_ID

SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT(USER_ID)) AS USERS
FROM(
    SELECT B.* , R.GENDER
    FROM ONLINE_SALE B
    JOIN USER_INFO R
    ON B.USER_ID = R.USER_ID
    WHERE R.GENDER IS NOT NULL
) AS M
GROUP BY
    YEAR(SALES_DATE) , MONTH(SALES_DATE), GENDER
ORDER BY
    YEAR(SALES_DATE) , MONTH(SALES_DATE), GENDER
    
# SELECT * FROM ONLINE_SALE