WITH USERS AS(
    SELECT
        WRITER_ID,
        SUM(PRICE) AS TOTAL_SALES
    FROM
        USED_GOODS_BOARD
    WHERE
        STATUS = "DONE"
    GROUP BY WRITER_ID
    HAVING TOTAL_SALES >= 700000
)

SELECT 
    B.WRITER_ID,
    NICKNAME,
    TOTAL_SALES
FROM 
    USERS B
JOIN
    USED_GOODS_USER R
ON
    B.WRITER_ID = R.USER_ID
ORDER BY
    TOTAL_SALES