WITH MAX_REVIEWER AS(
    SELECT
        MEMBER_ID,
        COUNT(*) AS COUNT
    FROM
        REST_REVIEW
    GROUP BY
        MEMBER_ID
    ORDER BY
        COUNT DESC
    LIMIT
        1
)

SELECT
    P.MEMBER_NAME,
    B.REVIEW_TEXT,
    DATE_FORMAT(B.REVIEW_DATE,"%Y-%m-%d") AS REVIEW_DATE
FROM
    REST_REVIEW B
JOIN
    MAX_REVIEWER R
ON
    B.MEMBER_ID = R.MEMBER_ID
JOIN
    MEMBER_PROFILE P
ON
    R.MEMBER_ID = P.MEMBER_ID
ORDER BY
    B.REVIEW_DATE , B.REVIEW_TEXT