WITH CARS AS(
    SELECT
        DISTINCT(CAR_ID)
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE LIKE "2022-10%"
)

SELECT
    B.CAR_ID
FROM
    CAR_RENTAL_COMPANY_CAR B
JOIN
    CARS R
ON
    B.CAR_ID = R.CAR_ID
WHERE
    CAR_TYPE = "세단"
ORDER BY
    B.CAR_ID DESC