SELECT ID
    ,FISH_NAME
    ,LENGTH
FROM (
    SELECT 
        ID,
        LENGTH,
        FISH_TYPE,
        MAX(LENGTH) OVER (PARTITION BY FISH_TYPE) AS MAX_SIZE
    FROM FISH_INFO
) AS TEMP
JOIN FISH_NAME_INFO
ON TEMP.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
WHERE LENGTH = MAX_SIZE
ORDER BY ID