SELECT R.SCORE
    ,R.EMP_NO
    ,B.EMP_NAME
    ,B.POSITION
    ,B.EMAIL
FROM HR_EMPLOYEES B,(SELECT EMP_NO
    ,SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY SCORE DESC
    LIMIT 1
    )AS R
WHERE B.EMP_NO = R.EMP_NO


