WITH TEMP AS(
    SELECT
        DEPT_ID,
        ROUND(AVG(SAL),0) AS AVG_SAL
    FROM
        HR_EMPLOYEES
    GROUP BY
        DEPT_ID
)

SELECT
    TEMP.DEPT_ID,
    DEPT_NAME_EN,
    AVG_SAL
FROM
    TEMP
JOIN
    HR_DEPARTMENT
ON
    TEMP.DEPT_ID = HR_DEPARTMENT.DEPT_ID
ORDER BY AVG_SAL DESC